version: '3.7'
services:
    app:
        env_file: .env
        depends_on:
            - db
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 4288:4288
    db:
        env_file: .env
        image: mongo
        volumes:
            - db-data:/data/db
    mongo-express:
        env_file: .env
        depends_on:
            - db
        image: mongo-express
        ports:
            - 8081:8081
volumes:
    db-data: